### ISSUE TITLE
TCP client mode releases idle connections

### ISSUE THREAD

**Issue by mchrisb03** [arduino/wifishield#10]
Please see my notes in Issue 9 (Connection dies after a few seconds).

In the notes I indicated that the same type of problem exists in the client side of the code.

The change was only made to the server side of the code and the issue was closed by the developer.

Please correct the similar issue on the client side.

Please also provide instructions, files and/or tools to build the firmware so that the user base of this product can provide assistance.

Thanks and regards!

**Comment by kostecky** [comment]
I can confirm this issue as well. I would love to see some instructions to resolve issue #8 in this project so I can import the wifiHD project in to eclipse and solve this issue.

**Comment by animan9** [comment]
The file in firmware/wiFiHD/Release/WiFiHD.elf (which supposedly addresses #10) is 707KB and does not run for me. The previous version of the file in firmware/binary/WiFIHD.elf (Issue #9) is 397KB loads and runs. Does anyone test releases before posting?

**Comment by digitalandrew** [comment]
Was able to flash the commited code that was supposed to fix issue #10.  Still experiencing same problem described in issue 10 however.  Can it be confirmed whether or not this fix worked?

**Comment by mlafauci** [comment]
With the code commited on udp_dev branch it is possible to use Atmel AVR Studio 6 to build the code and verify that also issue #10 was resolved.
Did you try with the latest to firmware committed on udp_dev branch? Could you specifiy in details your test?
