### ISSUE TITLE
Wifi Server only accepts one client connection at a time.

### ISSUE THREAD

**Issue by kostecky** [arduino/wifishield#11]
If you load up the WiFiChatServer sketch that comes with the shield libraries you can only establish one client connection at a time. I'm assuming that you should be able to establish at least 4 (as MAX_SOCK == 4). I believe this may be a result of "WiFiClient WiFiServer::available(byte\* status)" always returning the first available socket, but I've re-written it so that it does a fair round-robin scheme and the issue remains. I believe this is something deeper within the library or firmware, but haven't had a chance to track it down.

Here is my code:

```
WiFiClient WiFiServer::available(byte* status)
{
  static int cycle_server_down = 0;
  const int TH_SERVER_DOWN = 50;
  // The socket we last returned - let's be fair here and round-robin.
  static int last_socket = 0;
  int sock = 0;

    for (int sock_count = 0 ; sock_count < MAX_SOCK_NUM; sock_count++)
    {
        // Look at the next socket first
        sock = (last_socket + 1 + sock_count) % MAX_SOCK_NUM;
        if (WiFiClass::_server_port[sock] == _port)
        {
          WiFiClient client(sock);
            uint8_t _status = client.status();
            uint8_t _ser_status = this->status();

            if (status != NULL)
              *status = _status;

            //server not in listen state, restart it
            if ((_ser_status == 0)&&(cycle_server_down++ > TH_SERVER_DOWN))
            {
              ServerDrv::startServer(_port, sock);
              cycle_server_down = 0;
            }

            if (_status == ESTABLISHED)
            {
                last_socket = sock;
                return client;  //TODO
            }
        }
    }

    return WiFiClient(255);
}
```

**Comment by chriddyp** [comment]
@mlafauci @kostecky, was this issue closed because of a fix in the library (do we need to update our firmware?) or we because of some other work around?

I'm having trouble with running multiple socket clients with the WiFi library that ships with the shield, and would love to know the status of this issue. 

Thanks a bunch!
