### ISSUE TITLE
WiFi shield drops bytes occasionally

### ISSUE THREAD

**Issue by tigoe** [arduino/wifishield#15]
I've had trouble with the WiFi shield occasionally dropping bytes when it makes a HTTP request.

You can see the phenomenon here: https://cosm.com/feeds/54858  There should be four feeds: temp, Humidity, Pressure and Light. The additional misspelled feeds are added by the Arduino with WiFi shield making a HTTP call and dropping some of the bytes when it makes the call.

The code that I'm using is here: https://github.com/tigoe/SensorExamples/blob/master/WiFiWeatherStation/WiFiWeatherStation.ino  It's based on the Pachube client example. The same code, but with the Ethernet library in place of the WiFi library, works perfectly every time.

**Comment by damellis** [comment]
Re-assigning.

**Comment by nibelungen** [comment]
Nearly same issue here.... Files above 20kb print to serial gets crazy.
I have written all infos down here: http://arduino.cc/forum/index.php/topic,127386.0.html
I just got my red fly wifi shield - download freezes sometimes within this file but resumes until the file is complete.
With the wifishield it continiously polls data and stops immediatly in beetween the testfile.

The download with an ethernet arduino works perfectly here too.

**Comment by nibelungen** [comment]
Nice to see how many people care about their product, is this shield really its money worth???
Yes its a kind of open source soft and hardware but when i buy an assembled shield i expect some kind of support for this piece of hard/software... I´ve made my part of debugging und sum up the issue - now it is the dev part to solve this issue and some kind of feedback is disirable.

 Thanks in advance.

**Comment by mlafauci** [comment]
Needs also enhancement committed on fork https://github.com/mlafauci/Arduino.git
