### ISSUE TITLE
Connection drop out if you try to receive data greater than about 20KB

### ISSUE THREAD

**Issue by Fede85** [arduino/wifishield#19]
This issue has been found by Bill Atkins trying to receive data >20KB from an HTTP server

**Comment by nibelungen** [comment]
....nice find - now assigned? Issue still explained some months ago.

https://github.com/arduino/wifishield/issues/15#issuecomment-10469023

Nothing happened so far.

Issue found by Bill Atkins?

**Comment by mlafauci** [comment]
Hi,
  the issue #15 has been committed on upd_dev branch.
We'll collapse the udp_dev branch on the master branch as soon as 
completed the test.

Il 14/01/2013 22:43, nibelungen ha scritto:

**Comment by moreindirection** [comment]
Where will the next stable release be announced?
