### ISSUE TITLE
After Client Connects and Disconnects Twice A Third Connection Cannot be Made

### ISSUE THREAD

**Issue by Steve771** [arduino/wifishield#20]
Hi everyone. My group is using the Arduino WiFi Shield and the Arduino Uno Rev 3 for a project and have run into some issues. 

When using a telnet client on a laptop to communicate to the Arduino that is acting as the server, we can successfully make a connection, send data or remain idle, then disconnect with no problem. The same for when we reconnect. But when we try to connect a third time, the Arduino does not accept the connection. 

We took a look at the sever status after the second disconnect from the server and it still returns 1, however no connection is made. 

Anyone else find this issue occurring?

Also, our project actually involves an Android phone being the client and sending data to the Arduino. We have no issues making the initial connection, however if the connection is lost (either from the client closing the socket or the server dropping the client), we cannot reconnect to the server and the server status returns 0 after the disconnect; unlike the first issue mentioned when using a telnet client on a laptop. Here we cannot even make one reconnection. The server goes dead after the first client disconnects.

Here is the code we are using in our void loop:

void loop() {
  // wait for a new client:
  WiFiClient client = server.available();

  if(!client.connected() && count>0){///////////////////////////////////////////////////////////
    Serial.println("Client Disconnected");
    delayMicroseconds(5000);
    client.flush();
    client.stop();
    count--;
    server.begin();
  }
  // when the client sends the first byte, say hello:
  if (client) {
    if (!alreadyConnected) {
      // clead out the input buffer:
      client.flush();  
      Serial.println("We have a new client");
      client.println("Hello, client!"); 
      alreadyConnected = true;
      count++;  
    } 
    while (client.available() > 0) {  
      readTelnetcommand(client.read()); 

   }//end of while loop
  }// end of if 
 }//end main loop

On the Android it simply opens a socket specifying the IP of the Arduino and the port it is listening on and writes to its output stream whatever we want to sent to the Arduino and we are having no issues with the connection. As soon as the Android uses the command soc.close(), the Arduino ends the while loop for the client being connected, prints to the serial monitor that the client has disconnected, and we try the server.begin() command to try and force the server to look for incoming connections again but still no luck.

Any help is much appreciated. Also if you see any inefficient, improper, or illogical coding please let us know because programming is not our strong area.

Thanks

**Comment by mlafauci** [comment]
Commited fix on udp_dev branch that is under test
