### ISSUE TITLE
UDP client/server

### ISSUE THREAD

**Issue by mamaretti** [arduino/wifishield#22]
Hi, im looking for a way to communicate via UDP.

the official arduino page says it supportsUDP
(http://arduino.cc/en/Main/ArduinoWiFiShield)

but How? 
The Libary and Firmware doesn't have any UDP-Support right?

thx a lot

**Comment by Fede85** [comment]
Hi,
with the current production firmware there isn't the official support for the UDP connections. So, this means there is a mistake in the documentation.

However this feature has been implemented but is under testing. There is a specific branch called "udp_dev" (https://github.com/arduino/wifishield/tree/udp_dev) if you want to participate on testing.
