### ISSUE TITLE
WEP Connection issues

### ISSUE THREAD

**Issue by mbanzi** [arduino/wifishield#5]
Connecting to WEP networks is hard because the default method doesn't work and the message "Couldn't get a connection" is not very clear.

I spent an hour figuring out that if you have a WEP network you have to set the second parameter to 0 and the password needs to be in HEX...

we need better error reporting and the documentation has to cleary explain this

**Comment by tigoe** [comment]
See the new ConnectWithWEP example, it addresses most of these issues.  When Scott adds the WEP notes to the Getting Started Guide, it should address all of it.

**Comment by tigoe** [comment]
This seems to be addressed by Scott's writing in the Getting Started and the ConnectWithWEP example. Can we close it?
