### ISSUE TITLE
ScanNetworks example reports 0 values for RSSI and EncType

### ISSUE THREAD

**Issue by tigoe** [arduino/wifishield#6]
The ScanNetworks example reports 0 values for RSSI and Encryption Type on all networks it scans.

**Comment by mlafauci** [comment]
Hi Tom,
are you sure you are using the latest firmware posted and the latest 
wifiLibrary?
For the firmware you can check the build date you see on the console 
port on the wifi shield.
I tried some days ago with my shield and it worked.
Let me know.
Domenico

**Comment by tigoe** [comment]
I'm using version 1.0.2 of the firmware, and I downloaded the library a few minutes ago.  Am I on the right one?  I don't have a PC at home or a FTDI connector,  so I can't upgrade the firmware from here. But when I left work with this shield two days ago, it was running 1.0.2.

**Comment by tigoe** [comment]
oooh, wait, it looks like you made a modification to wifiHD.elf on the 6th.  Does that mean I need 1.0.3?

**Comment by mlafauci** [comment]
I am changing the build date. 
If you like I can increase the sw version, but I think the build date it is better to take trace of the changes.

**Comment by tigoe** [comment]
As long as I know what to look for when I upgrade the firmware, it's all good.

BTW, it might be good to make a function in the library that returns the firmware info. End users won't have the FTDI connector, and it's useful for troubleshooting, no?
