### ISSUE TITLE
WifiChatServer sends garbage

### ISSUE THREAD

**Issue by tigoe** [arduino/wifishield#7]
When I run the WifiChatServer, which is based on the Ethernet ChatServer, I can telnet into the server, but when I log in, I get a long string of garbage. Specifically, the server.print() line returns a long line of FFs as a result of the client.read().  This is not the same behavior I get from the Ethernet ChatServer example.  What's wrong?

**Comment by mlafauci** [comment]
I'll check

**Comment by tigoe** [comment]
Thanks. As long as you're at it, can you check the WifiTwitterClient and WIfiWebClient too?  When I have the ability to upgrade my firmware I will check them too.
