### ISSUE TITLE
Eclipse project creation problem: No file system is defined for scheme: framework

### ISSUE THREAD

**Issue by slopjong** [arduino/wifishield#8]
The "No file system is defined for scheme: framework" error message appears if I try to import the wifiHD project in eclipse 4.2.

I haven't tried much to fix the issue but as soon as I find out more I keep you up-to-date.

Worth readings:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=210664

**Comment by kostecky** [comment]
I'm having the exact same issue. I'd like to import the wifiHD firmware project as well.

**Comment by slopjong** [comment]
@kostecky  if you remember correctly we were chatting in irc 2 weeks ago and I was writing the ticket for you ;-)

**Comment by mlafauci** [comment]
Regarding "Eclipse project creation problem: No file system is defined for scheme: framework", the best way to develop and debug the WiFi library is to use the Atmel AvrStudio6.
I'll commit the project/solution files in order to import the project easily.

**Comment by slopjong** [comment]
AvrStudio6 is the best option for sure, for windows users.
